#!/usr/bin/env python

# TODO: Support Ctrl+C (KeyboardInterrupt)

from optparse import OptionParser
import keyring
import getpass

parser = OptionParser()
(options, args) = parser.parse_args()

password = keyring.get_password(args[0], args[1])

if password:
  print password
else:
 print 'Could not find a password in the keychain. Please provide one.'
 password = getpass.getpass()
 print password
 