#!/usr/bin/env bash
HOST="${1:---help}"

if [[ "$HOST" == "--help" ]]; then
  echo "Push a public key to a remote machine."
  echo ""
  echo "Usage: key-access [user@]hostname [key]"
  echo "Where key is the path to the public key."
  echo "key defaults to ~/.ssh/id_rsa.pub or ~/.ssh/id_dsa.pub"
else
  KEY=${2:-~/.ssh/id_?sa.pub}
  if [ -f $KEY ]; then
    ssh $HOST "mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys" < $KEY
    echo "Public key pushed."
 else
    echo "$KEY: No such file."
  fi
fi
