#!/usr/bin/env python
from optparse import OptionParser
import keyring
import getpass

parser = OptionParser()
(options, args) = parser.parse_args()

service = args[0]
username = args[1]

existing = keyring.get_password(service, username)

if existing:
  # TODO: add y/n prompt.
  print "Password entry exitst, will be overwritten."
  
if len(args) > 2:
  password = args[2]
else:
  password = getpass.getpass()

keyring.set_password(args[0], args[1], password)
